'use strict';
const DATA=[
['우주 반사경','반사경 면적','거울이 햇빛의 방향을 바꿔요.',['태양빛이 지구를 향해 와요.','거울에 닿은 빛이 옆으로 반사돼요.','지구에 도달하는 빛이 줄어요.'],'아주 큰 장치를 우주에 설치하고 유지해야 해요.'],
['성층권 에어로졸','입자 분사량','높은 하늘의 작은 입자가 햇빛을 돌려보내요.',['비행기가 높은 하늘에 입자를 뿌려요.','입자가 넓게 퍼져 층을 만들어요.','일부 햇빛이 우주로 되돌아가요.'],'비와 바람의 흐름이나 오존층에 영향을 줄 수 있어요.'],
['사막 반사판','반사판 설치 면적','사막 위 반사판이 햇빛을 되돌려 보내요.',['사막에 밝은 반사판을 설치해요.','햇빛이 반사판에 닿아요.','빛이 땅에 흡수되는 대신 위로 반사돼요.'],'넓은 땅을 덮으면 그곳의 생태계가 달라질 수 있어요.'],
['인공구름 만들기','해염 입자 분사량','작은 입자 주변에 물방울이 모여요.',['습한 공기에 배가 해염 입자를 뿌려요.','입자 주변에 물방울이 모여 구름이 돼요.','구름이 햇빛 일부를 반사해요.'],'구름이 생기기 좋은 공기 조건을 가정했어요.'],
['해상 구름 밝히기','해염 입자 공급량','같은 구름도 물방울이 달라지면 더 밝아져요.',['이미 있는 구름에 해염 입자를 보내요.','같은 양의 물이 더 많은 작은 물방울로 나뉘어요.','밝아진 구름이 햇빛을 더 반사해요.'],'실제로 얼마나 밝아지는지는 공기와 구름의 상태에 달려 있어요.'],
['바다 표면의 미세 기포','기포층 면적','하얀 기포층이 바다 위에서 빛을 반사해요.',['장치가 수면에 작은 기포를 만들어요.','기포가 모여 하얀 층을 이뤄요.','어두운 바닷물보다 빛을 더 반사해요.'],'기포는 사라지기 때문에 계속 만들어야 해요.'],
['건물 지붕 반사율 높이기','밝게 칠한 지붕 면적','도시의 어두운 지붕을 밝게 바꿔 햇빛을 더 반사해요.',['어두운 지붕이 햇빛을 흡수해 더워져요.','지붕과 옥상을 밝은 색으로 칠해요.','밝은 지붕이 햇빛을 우주로 더 되돌려보내요.'],'사람이 사는 건물에만 적용돼서 전 지구에 주는 효과는 작아요.'],
['높은 권운 줄이기','권운 줄이는 정도','햇빛 대신, 지구의 열이 빠져나가게 해요.',['땅에서 열이 위로 나가요.','높은 구름은 열을 흡수하고 다시 내보내요.','구름이 줄면 더 많은 열이 우주로 나가요.'],'실제 냉각 효과는 불확실하며 반대로 따뜻해질 수도 있어요.'],
['인공 나무','작동하는 필터 수','공기 속 CO₂를 잡아 저장소로 보내요.',['공기가 필터를 통과해요.','필터가 CO₂를 붙잡고 나머지 공기는 나가요.','모은 CO₂를 저장소로 보내요.'],'CO₂를 분리하고 오래 저장하는 데 에너지와 시설이 필요해요.'],
['이산화탄소 포집·저장','포집 장치 작동 규모','공장에서 나오기 전에 CO₂를 잡아요.',['공장의 배기가스가 포집 장치로 들어가요.','분리한 CO₂를 파이프로 보내요.','땅속 깊은 저장층에 모아요.'],'저장한 CO₂가 새지 않는지 오랫동안 살펴야 해요.'],
['철분 살포·심층수 올리기','영양분 공급량','플랑크톤이 탄소를 흡수하고 일부는 가라앉아요.',['철분이나 깊은 바다의 영양분을 공급해요.','플랑크톤이 자라며 물속 CO₂를 흡수해요.','일부 탄소는 가라앉고 일부는 다시 순환해요.'],'자란 플랑크톤이 모두 탄소 저장으로 이어지지는 않아요.']
];
const $=id=>document.getElementById(id), state={id:0,strength:50,compare:false,paused:false,mode:'iron',view:'space',hints:false,time:0};
let renderer,scene,camera,root,paths=[],labels=[],dynamic=[],yaw=0,pitch=.38,zoom=1,last=0;
const V=(x,y,z=0)=>new THREE.Vector3(x,y,z);
function mesh(geo,color,x=0,y=0,z=0){const m=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color,roughness:.62,metalness:.08}));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;root.add(m);return m;}
const box=(x,y,z,w,h,d,c)=>mesh(new THREE.BoxGeometry(w,h,d),c,x,y,z);
const ball=(x,y,z,r,c)=>mesh(new THREE.SphereGeometry(r,20,14),c,x,y,z);
function cylinder(x,y,z,r,h,c){return mesh(new THREE.CylinderGeometry(r,r,h,24),c,x,y,z);}
function label(text,x,y,z=0){const names={'표층에서 자라는 플랑크톤':'식물 플랑크톤','일부 탄소는 깊이 가라앉아요':'가라앉는 탄소','일부는 다시 표층으로':'다시 순환하는 탄소','땅 위에 세운 분무탑':'분무탑','하늘로 올려보낸 응결핵':'분무 입자','물방울이 모여 만든 새 구름':'새 구름','구름이 햇빛을 반사해요':'반사된 햇빛','모은 CO₂를 관으로':'CO₂ 수집관'};text=names[text]||text;const el=document.createElement('div');el.className='scene-name';el.textContent=text;el.setAttribute('aria-label',text);$('labels').append(el);labels.push({el,p:V(x,y,z)});}
function sprite(text,color){const c=document.createElement('canvas');c.width=128;c.height=64;const a=c.getContext('2d');a.fillStyle=color;a.beginPath();a.roundRect(0,0,128,64,24);a.fill();a.fillStyle='white';a.font='600 34px "Pretendard Variable", sans-serif';a.textAlign='center';a.fillText(text,64,45);const t=new THREE.CanvasTexture(c);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,depthTest:false,transparent:true}));s.scale.set(.62,.31,1);/* 글자는 어떤 선보다도 위에 — path 튜브가 renderOrder 1,2 라서 3 */s.renderOrder=3;root.add(s);return s;}
function path(points,color=0xd9a51b,type='light',count=2){const ps=points.map(p=>V(...p));const curve=new THREE.CurvePath();for(let i=1;i<ps.length;i++)curve.add(new THREE.LineCurve3(ps[i-1],ps[i]));/* nutrient: 물속에서도 보이도록 굵게 + 반투명 물에 가리지 않게 항상 위로 */const line=mesh(new THREE.TubeGeometry(curve,60,type==='pipe'?.055:type==='nutrient'?.036:.018,6,false),color);if(['pipe','co2','carbon','nutrient'].includes(type)){line.material.depthTest=false;line.renderOrder=1;}let marks=[];for(let i=0;i<count;i++){let m;if(type==='co2'||type==='carbon')m=sprite(type==='co2'?'CO₂':'탄소','#8147b8');else{const big=type==='nutrient';m=mesh(new THREE.ConeGeometry(big?.17:.09,big?.44:.25,8),color);if(big){m.material.depthTest=false;m.renderOrder=2;}}marks.push(m);}paths.push({curve,marks,type,offset:paths.length*.13});return line;}
function wavePath(points){const p=[];for(let j=0;j<points.length-1;j++){const a=V(...points[j]),b=V(...points[j+1]);for(let k=0;k<16;k++){const v=a.clone().lerp(b,k/16);v.x+=Math.sin(k/16*Math.PI*4)*.07;p.push(v.toArray());}}p.push(points.at(-1));path(p,0xe67737,'heat');}
function ground(color=0x95b987,y=-1.8){box(0,y,0,9,.4,3.6,color);}
function boat(x=-2.7){box(x,-1.1,.1,1.5,.38,.7,0xf4fafb);box(x,-.74,.1,.65,.42,.5,0x286b9b);cylinder(x+.4,-.55,.1,.07,.7,0xd7e7e9);}
function cloud(x,y,size=1,color=0xffffff){if(!LabVisuals.textures.cloud){const t=new THREE.TextureLoader().load(window.CLOUD_IMAGE);t.colorSpace=THREE.SRGBColorSpace;t.userData.shared=true;LabVisuals.textures.cloud=t;}const group=new DreiCloud.Clouds({texture:LabVisuals.textures.cloud,limit:18});const c=new DreiCloud.Cloud({seed:7,segments:18,bounds:V(1.1,.22,.38),volume:2.1,growth:.08,speed:.1,opacity:.8,fade:0,color:new THREE.Color(color)});group.add(c);group.position.set(x,y,0);group.scale.setScalar(size);root.add(group);let previous=state.time;dynamic.push(t=>{root.updateMatrixWorld(true);camera.updateMatrixWorld();group.update(camera,t,Math.max(0,Math.min(.05,t-previous)));previous=t;});return group;}
function pipe(points){path(points,0x748e9c,'pipe',0);}
/* cx: 광선 다발의 중심 x. 반사되는 광선은 가운데(장치가 있는 곳)부터 채운다. */
function sunRays(level,surface=-1.4,targetY=1.0,cx=0){const order=[2,1,3,0,4],n=Math.round(level*4);for(let i=0;i<5;i++){const x=cx-.94+i*.47,reflect=order.indexOf(i)<n;path([[x-1.3,3.1,-.5],[x,targetY,0],reflect?[x+1.1,3.1,.2]:[x+.4,surface,.25]]);}}
function clearScene(){if(root){scene.remove(root);const geometries=new Set(),materials=new Set(),textures=new Set();root.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material]){materials.add(m);for(const key of ['map','normalMap','specularMap'])if(m[key])textures.add(m[key]);}}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>{if(!t.userData.shared)t.dispose();});}root=new THREE.Group();scene.add(root);paths=[];dynamic=[];labels=[];$('labels').replaceChildren();}
function build(){if(!renderer)return;clearScene();renderer.shadowMap.needsUpdate=true;const id=state.id,a=(state.compare?0:state.strength)/100;scene.background=new THREE.Color(id===0?0x101e36:id===2?0xf2dfbd:[3,4,5,10].includes(id)?0xc7e7e9:0xdcebf5);$('inset').hidden=id!==4;$('ocean-modes').hidden=id!==10;LabVisuals.overlay();if(LabVisuals.build(id,a)){updateFrame();return;}
if(id===0){ball(-3.6,.2,0,.65,0xffc74f);const earth=ball(3.15,-.15,0,.85,0x3c88c6);for(let j=0;j<8;j++){const t=j*2.4;ball(3.15+Math.cos(t)*.6,-.15+Math.sin(t)*.55,.5,.22,0x76b886);}if(a>0){const m=box(0,.25,0,.12,.35+2.1*a,1.5,0xc3e5ff);m.rotation.z=-.3;box(0,-1.0,0,.15,.55,.15,0x7193b0);}for(let i=0;i<5;i++){const y=(i-2)*.36;const hit=a>0&&Math.abs(y-.25)<(.35+2.1*a)/2&&i!==0;path([[-2.9,y,0],[0,y,0],hit?[-1.5,2.8,.1]:[2.45,y,0]]);}label('태양',-3.6,1.15);label(a?'우주 반사경':'반사경 적용 전',0,1.85);label('지구',3.2,1.05);label('반사된 빛',-1.5,3.05);}
if(id===1){ground();box(0,1,0,7,.07,2,0xc4d8ec);for(let i=0;i<Math.round(a*75);i++)ball(-3+(i%15)*.42,1.12+Math.sin(i*2)*.18,Math.sin(i*3)*.65,.045,0xebedf6);box(-2.8,1.55,.2,1.2,.12,.18,0xf9fcff);box(-2.7,1.55,.2,.28,.06,.9,0x7695b3);if(a)path([[-2.2,1.5,0],[-1.7,1.1,0],[1.8,1.05,0]],0xa6a7cd,'spray');sunRays(a,-1.5,1.1);label('입자를 뿌리는 비행기',-2.7,2.15);label('높은 하늘의 입자층',1.8,1.75);label('지표',2.8,-1.3);}
if(id===2){ground(0xddb477);for(let i=0;i<12;i++){const x=-2.7+(i%4)*1.7,z=-.9+Math.floor(i/4)*.9;box(x,-1.48,z,1,.08,.65,0xc2a06a);if(i<Math.round(a*12)){const m=box(x,-1.25,z,1,.07,.65,0xe9f5ff);m.rotation.z=-.13;}}for(let i=0;i<4;i++){const x=-2.7+i*1.7;path([[x-1,3,0],[x,-1.2,0],i<Math.round(a*4)?[x+1.2,2.6,0]:[x,-1.5,0]]);}label('반사판 설치 구역',-.5,-.4,.9);label('사막',3.4,-1.4,1);}
if([3,4,5].includes(id)){ground(0x279aaf,-1.6);boat();label('분무선',-2.8,-.3,.3);if(id!==5){const factor=id===3?a:1; if(factor>0){const g=cloud(.4,1.05,id===3?.5+factor*.6:1.15,id===4?new THREE.Color().lerpColors(new THREE.Color(0xaab8c8),new THREE.Color(0xffffff),a):0xffffff);if(id===3)dynamic.push(t=>g.scale.setScalar(.85+.15*Math.min(1,t/5)));}if(a)path([[-2.3,-.55,.1],[-1.9,.3,.1],[-.7,1.05,.1]],0x72afc8,'spray',3);sunRays(.2+a*.65,-1.3,1,.4);label('들어오는 햇빛',-2.5,2.7);label('이미 있던 구름',.5,1.95);if(a)label('구름이 햇빛을 반사해요',1.7,2.95);label('바다',3,-1.15,1);/* 물의 양은 고정 막대로 '안 변하는 것'을 눈에 보이게 하고, 옆에 반사 겉넓이 막대를 같이 둔다.
   같은 물을 잘게 나눌수록 겉넓이는 넓어진다: 겉넓이 ∝ n·r², r ∝ (1/n)^(1/3) → ∝ n^(1/3) */
if(id===4){const n=4+Math.round(a*12),r=20*Math.cbrt(4/n),area=Math.round(Math.cbrt(n/16)*100);const bar=(name,w,note,grow)=>'<em>'+name+'</em><span class="bar"><span class="fill'+(grow?' grow':'')+'" style="width:'+w+'%"></span></span><small>'+note+'</small>';$('inset').innerHTML='<b>구름 속 확대</b><div class="drops">'+Array.from({length:n},()=>'<i style="width:'+r+'px;height:'+r+'px"></i>').join('')+'</div><div class="bars">'+bar('물의 양',100,'그대로')+bar('반사 겉넓이',area,(area/63).toFixed(1)+'배',true)+'</div><span>물방울 '+n+'개 · 잘게 나눌수록 겉넓이가 넓어져 햇빛을 더 반사해요</span>';}}else{for(let i=0;i<Math.round(a*90);i++)ball(-.8+(i%10)*.35,-1.24+Math.sin(i)*.035,-.95+Math.floor(i/10)*.22,.10,0xf4ffff);for(let i=0;i<4;i++){const x=-.8+i*.9;path([[x-.7,3,0],[x,-1.15,0],i<Math.round(a*3)?[x+1.2,2.7,0]:[x,-1.5,0]]);}if(a)path([[-2.2,-1.2,.1],[-1,-1.2,.1],[1,-1.2,.1]],0xe7ffff,'spray');label('수면의 하얀 기포층',.8,-.65,1);label('어두운 바닷물',3.1,-1.1,1);}}
if(id===6){ground(0xadc2b5);for(let i=0;i<8;i++){const x=-2.9+(i%4)*1.85,z=i<4?.7:-.7,h=.7+(i%3)*.25;box(x,-1.55+h/2,z,1.15,h,.9,0xe4d8c7);box(x,-1.5+h,z,1.3,.09,1.05,i<Math.round(a*8)?0xffffff:0x4c5966);for(let j=0;j<2;j++)box(x-.25+j*.5,-1.25+h/2,z+.46,.18,.22,.015,0x7eabc0);if(i<4)path([[x-.6,3,z],[x,-1.42+h,z],i<Math.round(a*8)?[x+.65,2.6,z]:[x,-1.5+h,z]]);}label('흰 지붕 / 어두운 지붕',0,1.25,1);label('도시',3.3,-1.2,1);}
if(id===7){ground();const g=cloud(0,1.0,1.35,0xeef5ff);g.scale.set(1-.75*a,.25,1);for(let i=0;i<4;i++){const x=-2+i*1.35;if(i<1+Math.round(a*2))wavePath([[x,-1.4,0],[x,1,0],[x+.2,3.1,0]]);else{wavePath([[x,-1.4,0],[x,1,0]]);wavePath([[x+.18,.9,.1],[x+.6,-1.3,.1]]);wavePath([[x-.15,1.1,0],[x-.4,3,0]]);}}label('얇고 높은 권운',0,1.7);label('지표에서 나오는 열',-2,-.9);label('우주로 나가는 열',2.8,3.05);}
if(id===8){ground(0xc3d3bd);for(let i=0;i<3;i++){box(-.7,-.45,-.85+i*.85,.7,2,.55,0xd7e4e7);for(let j=0;j<6;j++)box(-.7,-1.1+j*.27,-.55+i*.85,.5,.06,.03,i<Math.ceil(a*3)?0x308b95:0x7e8e96);}cylinder(2.7,-.65,0,.55,1.65,0xb4c5df);for(let j=0;j<Math.round(a*6);j++)ball(2.5+(j%2)*.3,-1.2+Math.floor(j/2)*.25,.5,.09,0x9258ba);pipe([[-.7,-1.35,.4],[1,-1.35,.4],[2.7,-1.35,0],[2.7,-.4,0]]);for(let i=0;i<4;i++){const y=-.5+i*.38;if(i<Math.round(a*3))path([[-4,y,.4],[-.7,y,.4],[-.7,-1.35,.4],[1,-1.35,.4],[2.7,-1.35,0],[2.7,-.4,0]],0x9258ba,'co2',1);else path([[-4,y,.4],[-.7,y,.4],[3.8,y+.9,.4]],0x9258ba,'co2',1);}path([[-3,1.3,-.3],[-.7,1.3,-.3],[2.8,1.8,-.3]],0x76adb9,'air');label('공기 속 CO₂',-3,1.6);label('CO₂ 필터',-.7,1.35);label('모은 CO₂',2.7,.6);label('나머지 공기',2.9,2.2);}
if(id===9){box(0,-1.25,0,9,.4,2.8,0xa4b68c);box(0,-1.8,0,9,.65,2.8,0xc6aa81);box(0,-2.3,0,9,.35,2.8,0x8e7865);box(0,-2.7,0,9,.4,2.8,0xd3bc98);box(-2.8,-.55,0,1.8,1,1.1,0xb5c4cf);cylinder(-3,.35,0,.17,1.1,0x8f9ca9);box(-.3,-.4,0,.9,1.4,.8,0x85b7c0);pipe([[-3,.9,.45],[-.3,.9,.45],[-.3,-.3,.5],[2,-.3,.5],[2,-2.6,1.5],[3.4,-2.6,1.5]]);for(let i=0;i<4;i++)path(i<Math.round(a*3)?[[-3,.9,.5],[-.3,.9,.5],[-.3,-.3,.5],[2,-.3,.5],[2,-2.6,1.5],[3.4,-2.6,1.5]]:[[-3,.9,.5],[-2.9,1.6,.5],[-1+i*.7,2.8,.5]],0x9258ba,'co2',1);label('공장 배기가스',-3,1.4);label('포집 장치',-.3,1.15);label('주입 파이프',2,.45);label('모은 CO₂ · 깊은 저장층',2.2,-2.0,1.5);}
if(id===10){const waterSection=box(0,-1.25,-.6,9,2.8,.3,0xc3dce0);waterSection.material.transparent=true;waterSection.material.opacity=.15;waterSection.material.depthWrite=false;waterSection.castShadow=false;box(0,.15,0,9,.10,2.4,0x92dce0);box(0,-2.8,0,9,.25,2.5,0xb7bba2);if(state.mode==='iron'){const before=root.children.length;boat(-2.8);for(const m of root.children.slice(before))m.position.y+=1.4;if(a)for(let k=0;k<Math.round(a*10);k++){const particle=ball(-1.85+Math.sin(k)*.07,.55,.35,.045,0xb78c32);particle.userData.ironParticle=true;dynamic.push(t=>particle.position.y=.65-((t*.4+k/10)%1)*.4);}label('철분 공급',-2.8,1.7,1);}else{box(0,-2.35,.1,9,.7,2,0x2f6a50);/* 영양분은 금색 — 어두운 심해 바닥·짙은 물에서도 눈에 띄게(2D 도식과 같은 색 계열) */for(let i=0;i<14;i++)ball(-4+ (i%7)*1.2,-1.94+Math.sin(i)*.05,.1+Math.floor(i/7)*.55,.08,0xe8b654);pipe([[-2.8,-2.4,.5],[-2.8,.1,.5],[-.2,.1,.5]]);if(a)path([[-2.8,-2.3,.55],[-2.8,-.5,.55],[-2.4,.08,.55],[-.4,.04,.55]],0xf2b736,'nutrient',4);label('깊은 바다의 영양분',-3,-2.3,.7);label('펌프로 영양분을 끌어올려요',-1.7,-.7,.6);}path([[1,2.3,.5],[1,.3,.5],[.2,-.3,.6]],0x9258ba,'co2',2);path([[.2,-.5,.6],[.7,-1.05,.7]],0xb79a72,'carbon',1);path([[.7,-1.3,.7],[1,-1.8,.8],[1.4,-2.55,.9]],0xb79a72,'carbon',1);path([[.5,-.4,.7],[2,-.8,.7],[3,-.2,.7]],0x7b60a0,'carbon',1);path([[3,-.2,.7],[3.4,.4,.7],[3.7,1.8,.7]],0x9258ba,'co2',1);label('대기 속 CO₂',1,2.8);label('표층에서 자라는 플랑크톤',.6,.35,1);label('사체·배설물의 응집',.7,-1.15,1);label('일부 유기물 입자가 가라앉아요',.6,-2.3,1);label('일부는 다시 표층으로',2.9,-.9,1);}
LabVisuals.enhance(id,a);updateFrame();}
function cameraHome(){state.view='space';yaw=state.id===0?.08:state.id===8||state.id===9||state.id===10?.22:.35;pitch=state.id===0?.14:state.id===10?.5:state.id===8||state.id===9?.25:.5;zoom=1;document.querySelectorAll('[data-camera]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.camera==='space'));setCamera();}
function setCamera(){if(!camera)return;const w=$('stage').clientWidth,h=$('stage').clientHeight;if(!w||!h)return;const aspect=w/h;camera.aspect=aspect;const target=V(state.id===0?-1.75:0,state.id===0?.6:state.id===8?-.55:state.id===9?-.1:.25,0),dir=V(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)).normalize();camera.position.copy(target.clone().add(dir));camera.lookAt(target);camera.updateMatrixWorld();const right=V(1,0,0).applyQuaternion(camera.quaternion),up=V(0,1,0).applyQuaternion(camera.quaternion),tan=Math.tan(THREE.MathUtils.degToRad(camera.fov/2));let distance=0;for(const x of (state.id===0?[-8.55,4.1]:[-4.7,4.7]))for(const y of [state.id===0?-2.2:state.id===8||state.id===9||state.id===10?-3.2:-2,state.id===8?2.05:3.3])for(const z of (state.id===0?[-2.2,2.2]:[-2,2])){const p=V(x,y,z).sub(target);distance=Math.max(distance,Math.abs(p.dot(right))/(tan*aspect)+p.dot(dir),Math.abs(p.dot(up))/tan+p.dot(dir));}camera.position.copy(target.addScaledVector(dir,distance*1.06*zoom));camera.updateProjectionMatrix();camera.updateMatrixWorld();}
function updateFrame(){if(!renderer)return;for(const p of paths){p.marks.forEach((m,i)=>{const u=(state.time*.075+i/p.marks.length+p.offset)%1;const pos=p.curve.getPoint(u);m.position.copy(pos);if(!['co2','carbon'].includes(p.type)){m.quaternion.setFromUnitVectors(V(0,1,0),p.curve.getTangent(u).normalize());}else{const fade=Math.min(1,u*12,(1-u)*12);m.material.opacity=fade;}});}dynamic.forEach(f=>f(state.time));camera.updateMatrixWorld();const w=$('stage').clientWidth,h=$('stage').clientHeight;const occupied=[];for(const l of labels){const p=l.p.clone().project(camera);l.el.hidden=p.z>1;const lw=l.el.offsetWidth||140,lh=l.el.offsetHeight||30;const x=Math.max(lw/2+8,Math.min(w-lw/2-8,(p.x*.5+.5)*w));let yy=Math.max(lh/2+8,Math.min(h-lh/2-8,(-p.y*.5+.5)*h));for(let pass=0;pass<labels.length*2;pass++){const q=occupied.find(q=>Math.abs(q.x-x)<(q.w+lw)/2+7&&Math.abs(q.y-yy)<(q.h+lh)/2+6);if(!q)break;const below=q.y+(q.h+lh)/2+7;yy=below<=h-lh/2-8?below:Math.max(lh/2+8,q.y-(q.h+lh)/2-7);}occupied.push({x,y:yy,w:lw,h:lh});l.el.style.left=x+'px';l.el.style.top=yy+'px';}if(state.id!==7&&state.view!=='front')renderer.render(scene,camera);}
function sync(){document.body.dataset.preview='space';document.body.dataset.scene=String(state.id);const d=Features.data();$('number').textContent=String(state.id===10&&state.mode==='up'?12:state.id+1).padStart(2,'0')+' / 12';$('title').textContent=d[0];$('principle').textContent=d[2];$('steps').replaceChildren(...d[3].map(t=>{const l=document.createElement('li');setHighlightedText(l,t,d[6]||[]);return l;}));setHighlightedText($('limit'),d[4],d[6]||[]);setHighlightedText($('model-condition'),d[5]||'',d[6]||[]);$('strength-label').textContent=d[1];$('strength').value=state.compare?0:state.strength;$('strength').disabled=state.compare;$('strength').setAttribute('aria-valuetext',state.compare||state.strength===0?'개입 없음':state.strength<35?'작은 규모':state.strength<70?'중간 규모':'큰 규모');$('compare').textContent=state.compare?'내 설정으로 돌아가기':'작동 전과 비교';$('compare').setAttribute('aria-pressed',state.compare);$('pause').textContent=state.paused?'재생':'일시정지';$('pause').setAttribute('aria-pressed',state.paused);document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mode===state.mode));document.querySelectorAll('[data-category]').forEach(b=>{b.classList.toggle('selected',+b.dataset.category===(state.id<8?0:1));b.setAttribute('aria-pressed',+b.dataset.category===(state.id<8?0:1));});Features.navigation();LabVisuals.overlay();}
function select(id,mode='iron'){state.id=id;state.strength=50;state.compare=false;state.paused=false;state.time=0;state.mode=mode;sync();cameraHome();build();const e=document.querySelector('.experiment');e.classList.remove('changing');void e.offsetWidth;e.classList.add('changing');}
$('strength').oninput=e=>{state.strength=+e.target.value;sync();build();};$('compare').onclick=()=>{state.compare=!state.compare;sync();build();};$('pause').onclick=()=>{state.paused=!state.paused;sync();};$('view').onclick=()=>{cameraHome();updateFrame();};$('reset').onclick=()=>{select(state.id,state.mode);if($('navigation-dialog').open)$('navigation-dialog').close();};document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>select(+b.dataset.category?8:0));document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;state.time=0;sync();build();});
try{if(typeof THREE==='undefined')throw Error('Three.js 로딩 실패');renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;scene=new THREE.Scene();scene.add(new THREE.HemisphereLight(0xffffff,0x536e79,1.5));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(-4,8,5);light.castShadow=true;light.shadow.mapSize.set(1024,1024);light.shadow.camera.left=-7;light.shadow.camera.right=7;light.shadow.camera.top=7;light.shadow.camera.bottom=-7;light.shadow.normalBias=.03;scene.add(light);renderer.shadowMap.enabled=true;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;camera=new THREE.PerspectiveCamera(38,1,.1,100);$('stage').prepend(renderer.domElement);renderer.domElement.setAttribute('aria-label','선택한 기술의 3D 작동 모형');const resize=()=>{LabVisuals.overlay();renderer.setSize($('stage').clientWidth,$('stage').clientHeight);setCamera();updateFrame();};new ResizeObserver(resize).observe($('stage'));const pointers=new Map();let previous=null,gestureType='mouse';const metrics=()=>{const p=[...pointers.values()];return p.length>=2?{distance:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),x:(p[0].x+p[1].x)/2,y:(p[0].y+p[1].y)/2}:p[0];};renderer.domElement.style.touchAction='none';renderer.domElement.onpointerdown=e=>{if(e.pointerType==='mouse'&&e.button!==0)return;gestureType=e.pointerType||'mouse';pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});previous=metrics();renderer.domElement.setPointerCapture(e.pointerId);};renderer.domElement.onpointermove=e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const next=metrics();if(pointers.size>=2&&previous&&previous.distance){zoom=Math.max(.65,Math.min(1.65,zoom*previous.distance/next.distance));}else if(previous&&previous.x!==undefined&&next&&next.x!==undefined){const sens=gestureType==='touch'?.0062:.005;/* 손가락/마우스가 잡은 지점을 따라 장면이 함께 도는 방향(가로·세로 동일 규칙) */yaw=Math.max(-1.15,Math.min(1.15,yaw-(next.x-previous.x)*sens));pitch=Math.max(.04,Math.min(1.1,pitch+(next.y-previous.y)*sens*.85));}previous=next;setCamera();};renderer.domElement.onpointerup=renderer.domElement.onpointercancel=e=>{pointers.delete(e.pointerId);previous=pointers.size?metrics():null;};renderer.domElement.addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey)return;e.preventDefault();zoom=Math.max(.65,Math.min(1.65,zoom+e.deltaY*.0007));setCamera();},{passive:false});
select(0);resize();function animate(t){const dt=Math.min((t-last)/1000,.05);last=t;if(!state.paused)state.time+=dt;updateFrame();requestAnimationFrame(animate);}requestAnimationFrame(animate);window.lab={state,select,renderer,camera,get zoom(){return zoom;},get root(){return root;},get paths(){return paths;}};}catch(e){$('failure').hidden=false;console.error(e);sync();}

$('zoom-in').onclick=()=>{zoom=Math.max(.65,zoom*.86);setCamera();};
$('zoom-out').onclick=()=>{zoom=Math.min(1.65,zoom/ .86);setCamera();};
document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>{if(b.dataset.camera==='front'){state.view='front';$('lesson-details').open=true;}else cameraHome();LabVisuals.overlay();});
const exhibit=document.querySelector('.experiment');
let ownedFullscreen=false,previousFocus=false,fullscreenFallback=false;
function setWideView(on){document.body.classList.toggle('focus',on);}
function fullscreenButton(on){const b=$('fullscreen'),name=on?'전체화면 종료':'전체화면으로 보기';b.setAttribute('aria-pressed',on);b.setAttribute('aria-label',name);b.title=name;b.innerHTML='<i data-lucide="'+(on?'minimize':'maximize')+'"></i>';LabVisuals.icons();}
$('fullscreen').onclick=async()=>{
 if(ownedFullscreen&&document.fullscreenElement){await document.exitFullscreen();return;}
 if(fullscreenFallback){fullscreenFallback=false;setWideView(previousFocus);fullscreenButton(false);return;}
 previousFocus=document.body.classList.contains('focus');setWideView(true);
 try{if(!exhibit.requestFullscreen)throw new Error('Fullscreen unavailable');await exhibit.requestFullscreen();ownedFullscreen=true;fullscreenButton(true);}
 catch(e){fullscreenFallback=true;fullscreenButton(true);$('fullscreen').title='넓게 보기 종료';$('fullscreen').setAttribute('aria-label','넓게 보기 종료');}
};
document.addEventListener('fullscreenchange',()=>{if(document.fullscreenElement===exhibit){ownedFullscreen=true;fullscreenButton(true);}else if(ownedFullscreen){ownedFullscreen=false;setWideView(previousFocus);fullscreenButton(false);}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.fullscreenElement){if(fullscreenFallback){fullscreenFallback=false;setWideView(previousFocus);fullscreenButton(false);}else if(document.body.classList.contains('focus'))setWideView(false);}});

Features.init();
