/* Hover/touch identification, explanatory SVG diagrams, and source-backed photos. */
window.Features={
 data(){if(state.id!==10)return DATA[state.id];return state.mode==='up'?['심층수 끌어올리기','심층수 공급량','깊은 바다의 영양분을 표층으로 올려요.',['파이프가 깊은 바닷물을 위로 올려요.','함께 올라온 영양분이 플랑크톤 성장을 도와요.','흡수한 탄소 일부는 가라앉고 일부는 다시 순환해요.'],'깊은 물의 CO₂도 함께 올라올 수 있어요.']:['바다에 철분 살포','철분 공급량','철분이 플랑크톤의 성장을 도와요.',['배가 바다 표면에 철분을 공급해요.','플랑크톤이 자라며 물속 CO₂를 흡수해요.','일부 탄소는 깊은 바다로 내려가요.'],'자란 플랑크톤이 모두 장기 탄소 저장으로 이어지지는 않아요.'];},
 oceanNavigation(){if(state.id<8)return;const b=document.createElement('button');b.innerHTML='<i data-lucide="arrow-up-from-line"></i><span>12</span>심층수 끌어올리기';b.classList.toggle('selected',state.id===10&&state.mode==='up');b.setAttribute('aria-pressed',state.id===10&&state.mode==='up');b.onclick=()=>select(10,'up');$('techniques').append(b);},
 overlay(){const is2d=state.view==='front'||state.id===7;const stage=$('stage');if(renderer)renderer.domElement.hidden=is2d;stage.dataset.mode=is2d?'diagram':'spatial';$('diagram').hidden=!is2d;$('view-kind').textContent=is2d?'2D 원리 도식':'3D 공간 모형';document.querySelectorAll('[data-camera]').forEach(b=>{b.disabled=state.id===7&&b.dataset.camera==='space';b.setAttribute('aria-pressed',b.dataset.camera===(is2d?'front':'space'));});[$('zoom-in'),$('zoom-out'),$('view')].forEach(b=>b.disabled=is2d);if(is2d&&state.id!==7)this.diagram();$('ocean-modes').hidden=true;$('inset').hidden=state.id!==4||is2d;stage.classList.toggle('paused',state.paused);$('scene-tooltip').hidden=true;this.syncHints();$('photos').hidden=![1,2,4,8,10].includes(state.id);$('cloud-context').hidden=![3,4].includes(state.id);$('cloud-context').textContent=state.id===3?'구름 없는 습한 공기 → 새 구름 만들기':'이미 있는 구름 → 물방울을 작고 많게';},
 diagram(){const id=state.id,a=(state.compare?0:state.strength)/100;const narrow=$('stage').clientWidth<600;let content='';
const tip=(name,shapes)=>`<g class="diagram-object" tabindex="0" role="button" aria-label="${name}" data-tip="${name}">${shapes}</g>`;
const rect=(x,y,w,h,c,rx=4)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rx}" fill="${c}" stroke="#365465" stroke-width="2.5" vector-effect="non-scaling-stroke"/>`;
const circ=(x,y,r,c)=>`<circle cx="${x}" cy="${y}" r="${r}" fill="${c}" stroke="#365465" stroke-width="2.5" vector-effect="non-scaling-stroke"/>`;
/* w: 굵기를 직접 정할 때. 안 주면 기존 규칙(보라 화살표는 강도에 따라 굵어짐) */
const line=(d,c='#d1a039',opacity=1,w=0)=>`<path class="diagram-flow" d="${d}" fill="none" stroke="${c}" stroke-width="${w||(c==='#9363b7'?4+6*a:4)}" opacity="${opacity}" vector-effect="non-scaling-stroke" marker-end="url(#diagram-arrow)"/>`;
const cloud=(x,y,s=1)=>`<g transform="translate(${x} ${y}) scale(${s})"><path d="M-70 20 Q-96-8-64-23 Q-50-61-16-38 Q12-78 42-35 Q86-42 88 1 Q90 27 58 28 H-50Z" fill="#fff" stroke="#365465" stroke-width="3" vector-effect="non-scaling-stroke"/></g>`;
const sea=()=>rect(0,295,800,185,'#9bd5dd')+`<path d="M0 296 Q100 285 200 296 T400 296 T600 296 T800 296" fill="none" stroke="#4293a3" stroke-width="3"/>`;
const ship=()=>tip(id===10?'철분 공급선':'분무선',rect(90,270,110,25,'#456c7e')+rect(112,243,47,27,'#f5f6ed'));
if(id===0){content+=tip('태양',circ(90,260,43,'#efbd56'))+tip('지구',`<image href="assets/earth-day.jpg" x="600" y="200" width="120" height="120" preserveAspectRatio="xMidYMid slice" clip-path="url(#earth-circle)"/>`+`<circle cx="660" cy="260" r="60" fill="none" stroke="#4d829e" stroke-width="4"/>`);/* 20° 기울인 거울: 수평으로 들어온 빛이 서로 나란히 위쪽으로 되튕긴다(정반사) */const mcx=358,mcy=265,half=a*70,tilt=Math.tan(20*Math.PI/180);if(a)content+=tip('우주 반사경',`<g transform="rotate(20 ${mcx} ${mcy})">${rect(mcx-8,mcy-half,16,half*2,'#8dbccf',4)}</g>`);let bounced=0;for(let i=0;i<6;i++){const y=190+i*30,hx=Math.round(mcx+(mcy-y)*tilt),hit=a>0&&Math.abs(y-mcy)<=half*.94;content+=line(`M140 ${y} H${hit?hx:588}`);if(hit){bounced++;content+=line(`M${hx} ${y} l-153 -129`);}}if(bounced)content+=`<text x="120" y="46" fill="#c9a659" font-size="17">거울에 닿은 빛은 우주로 되튕겨요</text>`;}
else if(id===8){/* 인공 나무 — 3D 와 같은 모습이고, 밑동이 모으는 관으로 탱크까지 이어진다 */content+=rect(0,380,800,100,'#b7cbb6');const ell=(cx,cy,rx,ry,rot,fill)=>`<ellipse cx="${cx}" cy="${cy}" rx="${rx}" ry="${ry}" transform="rotate(${rot} ${cx} ${cy})" fill="${fill}" stroke="#365465" stroke-width="2.5" vector-effect="non-scaling-stroke"/>`;[160,300,440].forEach((tx,ti)=>{const on=ti<Math.ceil(a*3),leaf=on?'#2f9f8a':'#aab6a9';let s=rect(tx-8,236,16,158,'#8b9483',5);for(let t=0;t<3;t++){const y=348-t*46,off=42-t*5;s+=`<path d="M${tx-off+8} ${y-15} H${tx+off-8}" stroke="#8b9483" stroke-width="5" fill="none" stroke-linecap="round"/>`;s+=ell(tx-off,y-19,off-16,10,-16,leaf)+ell(tx+off,y-19,off-16,10,16,leaf);}s+=ell(tx,228,22,9,0,leaf);content+=tip(on?'CO₂를 붙잡는 인공 나무 (작동 중)':'인공 나무 (아직 멈춰 있어요)',s);});content+=tip('나무들을 잇는 CO₂ 수집관',`<path d="M150 396 H660 V370" fill="none" stroke="#456d7e" stroke-width="19" stroke-linecap="round" stroke-linejoin="round"/><path d="M150 396 H660 V370" fill="none" stroke="#b9d2dc" stroke-width="14" stroke-linecap="round" stroke-linejoin="round"/>`);content+=tip('모은 CO₂ 저장 탱크',rect(615,255,100,115,'#dbe3e9',14));content+=rect(624,361-92*a,82,92*a,'#8256ad',6);for(let k=0;k<2+Math.round(a*6);k++)content+=circ(35+k*18,152,5,'#9164b2');content+=line('M52 174 Q104 204 132 222','#9363b7',.3+a*.7,5);content+=line('M84 126 Q340 66 552 98','#9363b7',1-a*.7,5);if(a)content+=line('M172 396 H660 V366','#9363b7',.3+a*.7,6);content+=`<text x="26" y="112" fill="#8153a9">CO₂</text>`;content+=`<text x="255" y="440" fill="#3f6070" font-size="15">모은 CO₂ 는 관을 타고 탱크로</text>`;}
else if(id===9){content+=rect(0,320,800,50,'#b9bc94')+rect(0,370,800,35,'#a38c73')+rect(0,405,800,75,'#d3bf9a');content+=tip('배출가스가 나오는 공장',rect(75,235,130,85,'#8198a3')+rect(105,160,22,80,'#587581'));content+=tip('CO₂를 분리하는 필터',rect(340,195,90,145,'#8cafb3')+[0,1,2,3].map(i=>rect(350,215+i*27,70,7,'#456f7c')).join(''));content+=tip('지하 저장층',rect(615,420,100,38,'#a392c0',18));content+=line('M150 200 H340','#9363b7');content+=line('M385 195 L520 100','#9363b7',1-a*.7);if(a)content+=line('M430 280 H590 V440 H615','#9363b7',.3+a*.7);content+=`<text x="200" y="181" fill="#8153a9">CO₂</text>`;content+=rect(627,447-22*a,76,22*a,'#8256ad',5);for(let k=0;k<3;k++)content+=circ(360+k*25,320,7,k<Math.ceil(a*3)?'#247d73':'#c7d1d1');for(let k=0;k<2+Math.round(a*6);k++)content+=circ(180+k*19,245,5,'#9164b2');}
else if(id===10){content+=sea();content+=rect(0,418,800,62,'#3f7a5c',0);content+=tip('표층에서 자라는 플랑크톤',Array.from({length:2+Math.round(a*12)},(_,i)=>circ(300+i%7*22,322+Math.floor(i/7)*16,5,'#3fa25c')).join(''));if(state.mode==='iron'){content+=ship();if(a)content+=line('M195 282 Q250 300 300 320','#b4874f',a);content+=`<text x="108" y="262" fill="#7a5a34" font-size="15">뿌리는 철분</text>`;}else{content+=tip('심층수 펌프',rect(150,305,18,130,'#628e9e'));content+=tip('깊은 바다의 영양분',Array.from({length:5},(_,i)=>circ(96+i*15,458,7,'#c79a4f')).join(''));if(a){content+=line('M159 435 V332 Q165 324 210 324 H296','#2f9f66');content+=`<text x="120" y="300" fill="#2c6b48" font-size="15">끌어올린 영양분</text>`;}}content+=line('M470 150 V300 L410 322','#9363b7');content+=`<text x="452" y="138" fill="#8153a9">CO₂</text>`;content+=line('M362 344 L432 448','#7b60a0');content+=`<text x="392" y="432" fill="#5c4a86" font-size="14">깊이 가라앉는 탄소</text>`;}
else{const ocean=[4,5].includes(id);content+=ocean?sea():rect(0,355,800,125,id===2?'#dbc49a':'#afc6b1');let hitY=335;
if(id===1){hitY=175;content+=tip('높은 하늘의 에어로졸 입자층',Array.from({length:Math.round(a*48)},(_,i)=>circ(260+i%12*23,165+Math.floor(i/12)*12,3,'#7c8fa7')).join(''));content+=tip('입자를 뿌리는 비행기',`<path d="M140 143 H240 L203 154 L187 177 L179 151 H140Z" fill="#668898"/>`);}
if(id===3){/* 바다가 아닌 육지 분무탑 — 4번(해상 구름)과 구분된다 */hitY=185;for(let i=0;i<8;i++){const x=40+i*95;if(x>105&&x<215)continue;content+=rect(x-4,338,8,22,'#7a6b4f')+circ(x,330,18,'#4c8f6e');}content+=tip('땅 위에 세운 분무탑',rect(120,338,60,18,'#c9d4da')+rect(143,214,14,126,'#8fa0ad')+rect(134,193,32,23,'#6f8ba7'));if(a){content+=tip('물방울이 모여 생긴 구름',cloud(415,180,.6+a*.4));content+=line('M170 200 Q262 176 350 182','#66a6bf',a);}}
if(id===4){hitY=185;content+=ship();content+=tip('이미 있는 해상 구름',cloud(415,180,1));if(a)content+=line('M173 247 Q220 215 340 193','#66a6bf',a);{content+=tip('같은 물의 양을 더 작은 물방울로 나눔',rect(580,305,165,90,'#f7fbff')+Array.from({length:4+Math.round(a*12)},(_,i)=>circ(600+i%6*23,329+Math.floor(i/6)*20,9*Math.cbrt(4/(4+Math.round(a*12))),'#64a1c2')).join(''));}}
if(id===5){hitY=295;content+=ship();content+=tip('수면의 하얀 미세 기포',Array.from({length:Math.round(a*50)},(_,i)=>circ(285+i%17*15,297+Math.floor(i/17)*9,5,'#f5fcff')).join(''));}
if(id===2){content+=tip('사막 반사판',Array.from({length:Math.round(a*6)},(_,i)=>rect(245+i*50,335,42,8,'#eaf4f7')).join(''));}
if(id===6){hitY=295;for(let i=0;i<5;i++)content+=tip(i<Math.round(a*5)?'햇빛을 반사하는 흰 지붕':'어두운 지붕',rect(230+i*65,300,50,55,'#e5e0d2')+rect(225+i*65,290,60,10,i<Math.round(a*5)?'#fff':'#526774'));}
if(id===2){
 for(let i=0;i<6;i++){const x=266+i*50,on=i<Math.round(a*6),y=on?335:355;
 content+=line(`M${x-55} 78 L${x} ${y}`);
 if(on)content+=line(`M${x} ${y} L${x+65} 85`);
 }
}else if(id===6){
 for(let i=0;i<5;i++){const x=255+i*65,on=i<Math.round(a*5);
 content+=line(`M${x-55} 78 L${x} 290`);
 if(on)content+=line(`M${x} 290 L${x+65} 85`);
 }
}else for(let i=0;i<4;i++){const x=375+i*25;content+=line(`M${x-55} 78 L${x} ${hitY}`);content+=line(i<Math.round(a*3)?`M${x} ${hitY} L${x+65} 85`:`M${x} ${hitY} V${ocean?318:355}`);}}
/* 글자가 화살표·선에 가리지 않도록 <text> 는 모두 맨 뒤로 옮겨 마지막에 그린다.
   테두리 색(--halo)은 그 도식의 배경색이라 어느 도식에서든 글자가 또렷하다. */
const bg=id===0?'#142339':'#e6f0f3',texts=[];content=content.replace(/<text\b[\s\S]*?<\/text>/g,m=>{texts.push(m);return '';})+texts.join('');
const h=narrow?520:480;$('diagram').innerHTML=`<svg style="--halo:${bg}" viewBox="0 0 800 ${h}" role="img" aria-label="${this.data()[0]} 원리 도식"><defs><marker id="diagram-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6" fill="none" stroke="context-stroke" stroke-width="1.5"/></marker><clipPath id="earth-circle"><circle cx="660" cy="260" r="60"/></clipPath></defs><rect width="800" height="${h}" fill="${bg}"/>${content}</svg>`;
if(narrow){const svg=$('diagram svg')||$('diagram').querySelector('svg');svg.setAttribute('viewBox','0 0 480 520');for(const child of svg.children)if(child.tagName!=='defs')child.setAttribute('transform','translate(0 15) scale(.6 .95)');}
},
 photos:[{name:'바다 위에 늘어선 실제 구름',image:'assets/real-clouds.jpg',description:'위성이 관측한 허드슨만의 구름입니다. 해수면 위의 수분과 바람이 구름 배열을 만드는 모습을 볼 수 있어요.',credit:'NASA · Jeff Schmaltz / MODIS Land Rapid Response Team, NASA GSFC',url:'https://science.nasa.gov/earth/earth-observatory/cloud-streets-pave-hudson-bay-6061/'},{name:'북대서양의 실제 플랑크톤 번성',image:'assets/real-bloom.jpg',description:'북대서양에서 자연적으로 식물 플랑크톤이 번성한 사진입니다. 철분 살포와 심층수 끌어올리기 모두 플랑크톤의 성장을 돕는 방법이라 같은 참고 사진을 사용해요. 두 기술을 실제로 시행한 결과 사진은 아닙니다.',credit:'NASA Earth Observatory · MODIS / Terra, 2010년 5월 22일',url:'https://science.nasa.gov/earth/earth-observatory/phytoplankton-bloom-in-the-north-atlantic-44073/'}],
 syncHints(){
 const on=state.hints,b=$('names-toggle');b.textContent=on?'이름 숨기기':'이름 보이기';b.setAttribute('aria-pressed',on);
 $('labels').hidden=!on;$('stage').classList.remove('hints-off');$('stage').classList.toggle('names-on',on);
 if(!$('diagram').hidden){
  const svg=$('diagram').querySelector('svg');
  if(svg){
   svg.querySelectorAll('.diagram-object').forEach(g=>{
    if(g.querySelector('.diagram-name'))return;
    const box=g.getBBox();if(!box.width&&!box.height)return;
    const text=document.createElementNS('http://www.w3.org/2000/svg','text');
    text.setAttribute('class','diagram-name');text.setAttribute('x',box.x+box.width/2);text.setAttribute('y',Math.max(25,box.y-12));text.setAttribute('text-anchor','middle');text.setAttribute('font-size','15');text.textContent=g.getAttribute('aria-label');g.append(text);
   });
   svg.querySelectorAll('text').forEach(text=>{if(text.textContent.trim()!=='CO₂'&&text.textContent.trim()!=='탄소')text.classList.add('diagram-name');});
  }
 }
 },

 photoIndex(){const map={4:0,10:1,1:2,2:3,5:4,8:5};return map[state.id]===undefined?0:map[state.id];},
 showPhoto(i){const p=this.photos[i];document.querySelector('.photo-note').textContent=i===1?'두 방법의 공통 대상인 플랑크톤을 보여주는 같은 자연 관측 사진입니다. 공급하는 영양분과 장치는 서로 달라요.':i===5?'2023년 12월 건설 중 촬영한 실제 시설 전경입니다. 체험 모형은 포집·저장 원리를 단순화한 것으로 실제 배치를 그대로 재현하지 않았습니다.':'자연현상 또는 관련 장치의 참고 사진입니다. 이 모형의 기술을 시행한 결과와는 구분해서 살펴보세요.';$('photo-image').src=p.image;$('photo-image').alt=p.name;$('photo-name').textContent=p.name;$('photo-description').textContent=p.description;$('photo-credit').textContent=p.credit;$('photo-source').href=p.url;$('photo-tabs').replaceChildren(...this.photos.map((p,j)=>{const b=document.createElement('button');b.textContent=['해상 구름','플랑크톤','성층권 에어로졸','사막 반사판','바다 거품','매머드'][j];b.setAttribute('aria-pressed',i===j);b.onclick=()=>this.showPhoto(j);b.hidden=j!==this.photoIndex();return b;}));},
 init(){$('names-toggle').onclick=()=>{state.hints=!state.hints;this.syncHints();};const stage=$('stage'),tip=$('scene-tooltip');const show=(text,x,y)=>{tip.textContent=text;tip.hidden=false;tip.style.left=Math.max(8,Math.min(stage.clientWidth-190,x+12))+'px';tip.style.top=Math.max(8,Math.min(stage.clientHeight-55,y-38))+'px';};const ray=new THREE.Raycaster();let down=null;
stage.addEventListener('pointerdown',e=>down={x:e.clientX,y:e.clientY});stage.addEventListener('pointermove',e=>{if(e.buttons)return;const r=stage.getBoundingClientRect(),target=e.target.closest('[data-tip]');if(target){show(target.dataset.tip,e.clientX-r.left,e.clientY-r.top);return;}if(e.target!==renderer?.domElement){tip.hidden=true;return;}ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObject(root,true).find(h=>h.object.visible&&h.object.isMesh&&!['TubeGeometry','ConeGeometry'].includes(h.object.geometry.type));if(!hit){tip.hidden=true;return;}let best=null,dist=Infinity;for(const l of labels){const d=l.p.distanceTo(hit.point);if(d<dist){dist=d;best=l;}}if(best&&dist<3)show(best.el.getAttribute('aria-label'),e.clientX-r.left,e.clientY-r.top);else tip.hidden=true;});stage.addEventListener('pointerleave',()=>tip.hidden=true);
stage.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>8)return;const t=e.target.closest('[data-tip]');if(t){const r=stage.getBoundingClientRect();show(t.dataset.tip,e.clientX-r.left,e.clientY-r.top);}});stage.addEventListener('focusin',e=>{const t=e.target.closest('[data-tip]');if(t){const r=stage.getBoundingClientRect(),b=t.getBoundingClientRect();show(t.dataset.tip,b.x-r.x+b.width/2,b.y-r.y);}});stage.addEventListener('focusout',()=>tip.hidden=true);
this.photos.push({name:'피나투보 분화 전후의 성층권 에어로졸층',image:'assets/real-aerosols.jpg',description:'위 사진은 1984년, 아래 사진은 1991년 피나투보 화산 분화 이후의 대기입니다. 아래 사진에 나타난 어두운 띠는 높은 대기의 에어로졸층이에요. 인공 살포 사진이 아니라 작동 원리를 이해하기 위한 자연 사례입니다.',credit:'NASA/JSC · STS41D-32-14, STS043-22-23',url:'https://science.nasa.gov/earth/earth-observatory/astronauts-photograph-mount-pinatubo/'});this.photos.push({name:'사막에 놓인 거대한 거울이 햇빛을 되쏘는 모습',image:'assets/real-desert-mirrors.jpg',description:'미국 모하비 사막에 있는 태양열 발전소의 거울밭입니다. 위성이 같은 곳을 두 방향에서 동시에 찍었어요. 왼쪽(46°)에서는 잘 보이지 않던 발전소가, 되쏜 햇빛이 카메라로 곧장 들어오는 오른쪽(26°)에서는 하얗게 빛납니다. 사막에 반사판을 깔면 햇빛이 이렇게 되돌아간다는 원리를 보여 주는 사례이며, 사막 반사판을 실제로 시행한 사진은 아닙니다.',credit:'NASA/GSFC/LaRC/JPL, MISR Team · Terra 위성 MISR, 2003년 4월 8일',url:'https://science.nasa.gov/earth/earth-observatory/sun-glint-from-solar-electric-generating-stations-4517'},{name:'거품이 생긴 곳만 밝게 보이는 실제 물 표면',image:'assets/real-foam.jpg',description:'투르크메니스탄의 얕고 짠 석호 가라보가즈굴을 위성이 찍은 사진입니다. 물속에서 거품이 만들어져 길게 모인 띠만 밝게 보이지요. 기포가 물을 하얗게 만들어 햇빛을 더 반사한다는 원리를 보여 주는 자연 사례이며, 미세 기포를 실제로 뿌린 사진은 아닙니다.',credit:'NASA Earth Observatory · Joshua Stevens, Landsat 8 OLI(USGS 자료), 2017년 4월 4일',url:'https://science.nasa.gov/earth/earth-observatory/lines-of-foam-on-garabogazkol-90206'});$('photos').onclick=()=>{this.showPhoto(this.photoIndex());$('photo-dialog').showModal();};$('close-photos').onclick=()=> $('photo-dialog').close();$('photo-dialog').addEventListener('click',e=>{if(e.target===$('photo-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});$('photo-dialog').addEventListener('close',()=> $('photos').focus());document.addEventListener('keydown',e=>{if(e.key==='Escape'){tip.hidden=true;document.querySelectorAll('.hotspot.active').forEach(e=>e.classList.remove('active'));}});
}
};
